# Generated by Django 2.2.4 on 2019-08-16 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotedgene',
            name='genes',
        ),
        migrations.DeleteModel(
            name='FunctionalAnnotation',
        ),
        migrations.DeleteModel(
            name='Organism',
        ),
        migrations.DeleteModel(
            name='AnnotedGene',
        ),
        migrations.DeleteModel(
            name='RealGene',
        ),
    ]
