# Generated by Django 2.2.4 on 2019-08-16 04:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_annotedgene_functionalannotation_organism_realgene'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotedgene',
            name='genes',
        ),
        migrations.AddField(
            model_name='annotedgene',
            name='id',
            field=models.AutoField(auto_created=True, null=True, blank=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
