# Generated by Django 2.2.4 on 2019-08-16 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_annotedgene'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotedGene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('de_gene', models.CharField(max_length=10)),
                ('log_fc', models.FloatField()),
                ('log_cpm', models.FloatField()),
                ('f', models.FloatField()),
                ('p_value', models.FloatField()),
                ('fdr', models.FloatField()),
            ],
            options={
                'verbose_name': 'Annotated gene',
                'verbose_name_plural': 'Annotated genes',
                'ordering': ['de_gene'],
            },
        ),
        migrations.CreateModel(
            name='Ortholog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orthogroup', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='realgene',
            name='de_genes',
            field=models.FileField(null=True, upload_to='', verbose_name='Differentially expressed genes'),
        ),
    ]
