# Generated by Django 2.2.4 on 2019-09-10 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190910_1214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genecorrespondences',
            old_name='organism',
            new_name='organism_design',
        ),
    ]
