# Generated by Django 2.2.4 on 2019-08-19 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190816_0201'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnnotedGene',
        ),
        migrations.RemoveField(
            model_name='organism',
            name='real_genes',
        ),
        migrations.DeleteModel(
            name='Ortholog',
        ),
        migrations.RemoveField(
            model_name='realgene',
            name='annotation',
        ),
        migrations.DeleteModel(
            name='FunctionalAnnotation',
        ),
        migrations.DeleteModel(
            name='Organism',
        ),
        migrations.DeleteModel(
            name='RealGene',
        ),
    ]
