# Generated by Django 2.2.4 on 2019-09-10 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190910_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genecorrespondences',
            old_name='organism_design',
            new_name='organism',
        ),
    ]
