# Generated by Django 2.2.4 on 2019-09-10 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190910_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='genecorrespondences',
            name='ortholog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Ortholog'),
        ),
    ]
