# Generated by Django 2.2.4 on 2019-08-19 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_analysisannotatedgene_organism_pannzer2annotation_realgene'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentalDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('condition_1', models.CharField(max_length=20)),
                ('condition_2', models.CharField(max_length=20)),
                ('replicate_number', models.IntegerField()),
                ('organism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Organism')),
            ],
        ),
    ]
