# Generated by Django 2.2.4 on 2019-09-11 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_genecorrespondences_ortholog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genecorrespondences',
            options={'verbose_name': 'Gene correspondences', 'verbose_name_plural': 'Gene correspondences'},
        ),
        migrations.RemoveField(
            model_name='genecorrespondences',
            name='annotation',
        ),
        migrations.RemoveField(
            model_name='genecorrespondences',
            name='gene',
        ),
        migrations.RemoveField(
            model_name='genecorrespondences',
            name='organism',
        ),
        migrations.RemoveField(
            model_name='genecorrespondences',
            name='ortholog',
        ),
        migrations.AddField(
            model_name='genecorrespondences',
            name='gene_organism_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gene_1', to='app.AnalysisAnnotatedGene'),
        ),
        migrations.AddField(
            model_name='genecorrespondences',
            name='gene_organism_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gene_2', to='app.AnalysisAnnotatedGene'),
        ),
        migrations.AddField(
            model_name='genecorrespondences',
            name='organism_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organism_1', to='app.ExperimentalDesign'),
        ),
        migrations.AddField(
            model_name='genecorrespondences',
            name='organism_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organism_2', to='app.ExperimentalDesign'),
        ),
        migrations.AddField(
            model_name='genecorrespondences',
            name='protein_organism_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='protein_1', to='app.Ortholog'),
        ),
        migrations.AddField(
            model_name='genecorrespondences',
            name='protein_organism_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='protein_2', to='app.Ortholog'),
        ),
    ]
