# Generated by Django 2.2.4 on 2019-09-11 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190911_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='genecorrespondences',
            name='design',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ExperimentalDesign'),
        ),
        migrations.AlterField(
            model_name='genecorrespondences',
            name='organism_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_1', to='app.Organism'),
        ),
        migrations.AlterField(
            model_name='genecorrespondences',
            name='organism_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_2', to='app.Organism'),
        ),
    ]
