# Generated by Django 2.2.4 on 2019-08-19 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_experimentaldesign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisannotatedgene',
            name='organism',
        ),
        migrations.RemoveField(
            model_name='pannzer2annotation',
            name='organism',
        ),
    ]
