# Generated by Django 2.2.4 on 2019-09-11 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190911_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ortholog',
            name='orthologs_organism_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ortholog_1', to='app.Pannzer2Annotation'),
        ),
        migrations.AlterField(
            model_name='ortholog',
            name='orthologs_organism_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ortholog_2', to='app.Pannzer2Annotation'),
        ),
    ]
