# Generated by Django 2.2.4 on 2019-09-12 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20190911_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genecorrespondences',
            name='protein_organism_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='protein_1', to='app.Pannzer2Annotation'),
        ),
        migrations.AlterField(
            model_name='genecorrespondences',
            name='protein_organism_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='protein_2', to='app.Pannzer2Annotation'),
        ),
    ]
