# Generated by Django 2.2.4 on 2019-08-19 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_ortholog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organism',
            name='annotation_reference_organism',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
