# Generated by Django 2.2.4 on 2019-08-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_ortholog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organism',
            name='family',
        ),
        migrations.RemoveField(
            model_name='organism',
            name='order',
        ),
        migrations.RemoveField(
            model_name='organism',
            name='phylum',
        ),
        migrations.RemoveField(
            model_name='organism',
            name='tax_class',
        ),
        migrations.AlterField(
            model_name='organism',
            name='annotation_reference_organism',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
