# Generated by Django 2.2.4 on 2019-09-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190912_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisannotatedgene',
            name='real_differential_expression',
            field=models.BooleanField(default=True),
        ),
    ]
