# Generated by Django 2.2.4 on 2019-08-20 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190819_2053'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RealGene',
        ),
    ]
