# Generated by Django 2.2.4 on 2019-08-20 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_delete_realgene'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealGene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession_number', models.CharField(max_length=20)),
                ('locus_tag', models.CharField(max_length=20)),
                ('organism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Organism')),
            ],
            options={
                'verbose_name': 'Real gene',
                'verbose_name_plural': 'Real genes',
                'ordering': ['accession_number'],
            },
        ),
    ]
