# Generated by Django 2.2.4 on 2019-08-20 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_realgene'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisannotatedgene',
            name='log_fc',
            field=models.FloatField(null=True),
        ),
    ]
