# Generated by Django 2.2.4 on 2019-09-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20190918_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pannzer2annotation',
            name='go_id',
            field=models.CharField(max_length=20),
        ),
    ]
