# Generated by Django 2.2.4 on 2019-08-20 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20190820_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ortholog',
            name='organism_1',
        ),
        migrations.RemoveField(
            model_name='ortholog',
            name='organism_2',
        ),
    ]
