# Generated by Django 2.2.4 on 2019-08-22 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20190822_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ortholog',
            name='organism_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organism_1', to='app.Organism'),
        ),
        migrations.AlterField(
            model_name='ortholog',
            name='organism_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organism_2', to='app.Organism'),
        ),
    ]
