# Generated by Django 2.2.4 on 2019-08-28 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20190822_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneCorrespondences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Pannzer2Annotation')),
            ],
            options={
                'verbose_name': 'Gene correspondences',
                'verbose_name_plural': 'Gene correspondences',
                'ordering': ['organism'],
            },
        ),
        migrations.AlterModelOptions(
            name='analysisannotatedgene',
            options={'ordering': ['log_fc', 'de_gene'], 'verbose_name': 'Analysis Annotated gene', 'verbose_name_plural': 'Analysis Annotated genes'},
        ),
        migrations.AlterModelOptions(
            name='ortholog',
            options={'ordering': ['orthogroup'], 'verbose_name': 'Orthogroup', 'verbose_name_plural': 'Orthogroups'},
        ),
        migrations.DeleteModel(
            name='RealGene',
        ),
        migrations.AddField(
            model_name='genecorrespondences',
            name='gene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.AnalysisAnnotatedGene'),
        ),
        migrations.AddField(
            model_name='genecorrespondences',
            name='organism',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Organism'),
        ),
    ]
